<a href="https://colab.research.google.com/github/ramandeepm0014/Superstore-Data-Analysis/blob/main/Sample_Superstore_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [31]:
('/content/drive/MyDrive/Colab Notebooks/Superstore Dataset.csv')

'/content/drive/MyDrive/Colab Notebooks/Superstore Dataset.csv'

In [32]:
import pandas as pd
pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Superstore Dataset.csv')

,Row ID,Order ID,Order Date,Ship Date,Customer Name,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,01-03-2023,01-07-2023,Darren Powers,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,FURNITURE,Bookcases,261.960,2,0.00,41.9136
1,2,US-2023-112326,01-04-2023,01-08-2023,Phillina Ober,Second Class,Consumer,United States,Henderson,Kentucky,42420,south,Furniture,Chairs,731.940,3,0.00,219.5820
2,3,US-2023-112326,01-04-2023,01-08-2023,Phillina Ober,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.620,2,0.00,6.8714
3,4,US-2023-112326,01-04-2023,01-08-2023,Phillina Ober,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,9999999.000,5,0.45,-383.0310
4,5,US-2023-141817,01-05-2023,01-12-2023,Mick Brown,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.368,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1002,794,US-2023-127691,7/22/2023,7/27/2023,Erin Mull,Standard Class,Consumer,United States,San Francisco,California,94110,West,Office Supplies,Labels,9.960,2,0.00,4.5816
1003,575,US-2023-141299,06-03-2023,06-07-2023,Ross Baird,Standard Class,Consumer,United States,Marysville,Washington,98270,West,Office Supplies,Art,8.820,3,0.00,2.3814
1004,3,US-2023-112326,01-04-2023,01-08-2023,Phillina Ober,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.620,2,0.00,6.8714
1005,262,US-2023-141838,3/26/2023,3/31/2023,Damala Kotsonis,Standard Class,Corporate,United States,Pasadena,Texas,77506,central,Office Supplies,Appliances,1.624,2,0.80,-4.4660
1006,4,US-2023-112326,01-04-2023,01-08-2023,Phillina Ober,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,9999999.000,5,0.45,-383.0310

In [33]:
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Superstore Dataset.csv')
df.head()

,Row ID,Order ID,Order Date,Ship Date,Customer Name,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,01-03-2023,01-07-2023,Darren Powers,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,FURNITURE,Bookcases,261.960,2,0.00,41.9136
1,2,US-2023-112326,01-04-2023,01-08-2023,Phillina Ober,Second Class,Consumer,United States,Henderson,Kentucky,42420,south,Furniture,Chairs,731.940,3,0.00,219.5820
2,3,US-2023-112326,01-04-2023,01-08-2023,Phillina Ober,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.620,2,0.00,6.8714
3,4,US-2023-112326,01-04-2023,01-08-2023,Phillina Ober,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,9999999.000,5,0.45,-383.0310
4,5,US-2023-141817,01-05-2023,01-12-2023,Mick Brown,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.368,2,0.20,2.5164

In [34]:
df.shape

(1007, 18)

In [35]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Customer Name',
       'Ship Mode', 'Segment', 'Country', 'City', 'State', 'Postal Code',
       'Region', 'Category', 'Sub-Category', 'Sales', 'Quantity', 'Discount',
       'Profit'],
      dtype='object')

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1007 entries, 0 to 1006
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         1007 non-null   int64
 1   Order ID       1005 non-null   object
 2   Order Date     1007 non-null   object
 3   Ship Date      1007 non-null   object
 4   Customer Name  1002 non-null   object
 5   Ship Mode      1007 non-null   object
 6   Segment        1007 non-null   object
 7   Country        1007 non-null   object
 8   City           1006 non-null   object
 9   State          1005 non-null   object
 10  Postal Code    1007 non-null   int64
 11  Region         1007 non-null   object
 12  Category       1007 non-null   object
 13  Sub-Category   1007 non-null   object
 14  Sales          1005 non-null   float64
 15  Quantity       1007 non-null   int64
 16  Discount       1007 non-null   float64
 17  Profit         1006 non-null   float64
dtypes: float64(3), int64(3), object(12)
memory usage: 141.7+ KB

In [37]:
df.isnull().sum()

Row ID           0
Order ID         2
Order Date       0
Ship Date        0
Customer Name    5
Ship Mode        0
Segment          0
Country          0
City             1
State            2
Postal Code      0
Region           0
Category         0
Sub-Category     0
Sales            2
Quantity         0
Discount         0
Profit           1
dtype: int64

In [38]:
df.duplicated().sum()

np.int64(6)

In [39]:
df['Region'].unique()

array(['South', 'south', 'West', 'WEST', 'Central', 'East', 'EAST',
       'central', 'SOUTH', 'west'], dtype=object)

In [40]:
df['Category'].unique()

array(['FURNITURE', 'Furniture', 'Office Supplies', 'OFFICE SUPPLIES',
       'Technology', 'technology', 'furniture', 'office supplies',
       'TECHNOLOGY'], dtype=object)

In [41]:
import numpy as np
print("Average Sales:", np.mean(df['Sales']))
print("Maximum Sales:", np.max(df['Sales']))
print("Minimum Sales:", np.min(df['Sales']))
print("Median Sales:", np.median(df['Sales']))
print("Sales Standard Deviation:", np.std(df['Sales']))
print("Total Sales:", np.sum(df['Sales']))

Average Sales: 35062.72142925374
Maximum Sales: 9999999.0
Minimum Sales: 1.08
Median Sales: nan
Sales Standard Deviation: 567586.1490108116
Total Sales: 35238035.036400005

## **Manual Data Cleaning**

Manual inspection was performed to identify missing values, duplicate records, inconsistent text formatting, extra spaces, invalid numerical values, outliers, and inconsistent date formats. The dataset was examined using functions such as head(), unique(), describe(), isnull().sum(), and duplicated().sum().

In [42]:
print("Before Cleaning:", df.shape)

Before Cleaning: (1007, 18)

In [43]:
df[df.isnull().any(axis=1)]

,Row ID,Order ID,Order Date,Ship Date,Customer Name,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
5,6,US-2023-167199,01-06-2023,01-10-2023,NaN,Standard Class,Consumer,United States,Los Angeles,California,90032,WEST,Furniture,Furnishings,48.860,7,0.0,14.1694
9,10,US-2023-167199,01-06-2023,01-10-2023,Maria Etezadi,Standard Class,Consumer,United States,NaN,California,90032,West,Office Supplies,Appliances,114.900,5,0.0,34.4700
13,14,US-2023-167199,01-06-2023,01-10-2023,NaN,Standard Class,Consumer,United States,Seattle,Washington,98103,West,Office Supplies,Binders,407.976,3,0.2,132.5922
15,16,NaN,01-07-2023,01-12-2023,Vivek Sundaresam,Standard Class,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Binders,2.544,3,0.8,-3.8160
18,19,US-2023-149020,01-10-2023,1/15/2023,NaN,Second Class,Consumer,United States,San Francisco,California,94109,West,Office Supplies,Art,8.560,2,0.0,2.4824
23,24,US-2023-157147,1/13/2023,1/18/2023,Brian Dahlen,Second Class,Consumer,United States,Philadelphia,NaN,19140,East,Furniture,Chairs,71.372,2,0.3,-1.0196
48,49,US-2023-167927,2023-20-11,1/26/2023,Xylona Preis,Standard Class,Consumer,United States,Dover,Delaware,19901,East,Technology,Phones,NaN,2,0.0,6.1040
77,78,US-2023-117163,1/27/2023,02-02-2023,NaN,First Class,Corporate,United States,Houston,Texas,77041,Central,Office Supplies,Storage,27.240,3,0.2,2.7240
118,119,US-2023-165589,2/18/2023,2/18/2023,NaN,Standard Class,Corporate,United States,Bristol,Tennessee,37620,South,Office Supplies,Binders,157.794,1,0.7,-115.7156
128,129,US-2023-137680,2/24/2023,03-02-2023,Jennifer Halladay,Second Class,Home Office,United States,Los Angeles,NaN,90004,West,Furniture,Chairs,81.424,2,0.2,-9.1602
218,219,US-2023-145317,3/18/2023,3/23/2023,Sean Miller,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,NaN,3,0.2,22.6782
283,284,US-2023-101770,3/31/2023,04-04-2023,Karen Bern,Standard Class,Consumer,United States,Portland,Oregon,97206,West,Office Supplies,Paper,141.760,5,0.2,NaN
299,300,NaN,04-03-2023,04-08-2023,Katrina Edelman,Standard Class,Corporate,United States,Belleville,New Jersey,7109,East,Office Supplies,Storage,1082.480,8,0.0,10.8248

In [44]:
df = df.dropna()

In [45]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Customer Name    0
Ship Mode        0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Category         0
Sub-Category     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [46]:
df = df.drop_duplicates()

In [47]:
df.duplicated().sum()

np.int64(0)

In [48]:
df['Region'] = df['Region'].str.strip().str.title()

In [49]:
df['Category'] = df['Category'].str.strip().str.title()

In [50]:
df['Customer Name'] = df['Customer Name'].str.strip()
df['City'] = df['City'].str.strip().str.title()
df['State'] = df['State'].str.strip().str.title()

In [51]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Customer Name    0
Ship Mode        0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Category         0
Sub-Category     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [52]:
print("After Cleaning:", df.shape)

After Cleaning: (988, 18)

# **Automatic Data Cleaning**

In [53]:
df = df.dropna(subset=['Order ID'])

In [54]:
df['Customer Name'] = df['Customer Name'].fillna(
    df['Customer Name'].mode()[0]
)

In [55]:
df['City'] = df['City'].fillna(
    df['City'].mode()[0]
)

In [56]:
df['State'] = df['State'].fillna(
    df['State'].mode()[0]
)

In [57]:
df['Sales'] = df['Sales'].fillna(
    df['Sales'].mean()
)

In [58]:
df['Profit'] = df['Profit'].fillna(
    df['Profit'].mean()
)

In [59]:
df = df.drop_duplicates()

In [60]:
df['Region'] = df['Region'].str.strip().str.title()

In [61]:
df['Category'] = df['Category'].str.strip().str.title()

In [62]:
for col in df.select_dtypes(include='object'):
    df[col] = df[col].str.strip()

In [65]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Customer Name    0
Ship Mode        0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Category         0
Sub-Category     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [66]:
df.duplicated().sum()

np.int64(0)

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 987 entries, 0 to 999
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         987 non-null    int64
 1   Order ID       987 non-null    object
 2   Order Date     987 non-null    object
 3   Ship Date      987 non-null    object
 4   Customer Name  987 non-null    object
 5   Ship Mode      987 non-null    object
 6   Segment        987 non-null    object
 7   Country        987 non-null    object
 8   City           987 non-null    object
 9   State          987 non-null    object
 10  Postal Code    987 non-null    int64
 11  Region         987 non-null    object
 12  Category       987 non-null    object
 13  Sub-Category   987 non-null    object
 14  Sales          987 non-null    float64
 15  Quantity       987 non-null    int64
 16  Discount       987 non-null    float64
 17  Profit         987 non-null    float64
dtypes: float64(3), int64(3), object(12)
memory usage: 146.5+ KB

In [70]:
df['Region'].unique()

array(['South', 'West', 'Central', 'East'], dtype=object)

In [71]:
df['Category'].unique()

array(['Furniture', 'Office Supplies', 'Technology'], dtype=object)

In [73]:
df.to_csv('Cleaned_Superstore.csv', index=False)

# **The 10 Business Questions & Answers**


# Q1. Which product sub-categories are generating losses despite high sales?

In [74]:
loss_products = df.groupby('Sub-Category')[['Sales','Profit']].sum().reset_index()

loss_products = loss_products[loss_products['Profit'] < 0]

loss_products = loss_products.sort_values(
    by='Sales',
    ascending=False
)

loss_products

   Sub-Category         Sales     Profit
16       Tables  1.002352e+07 -3451.9747
11     Machines  3.262212e+04 -4951.3543
4     Bookcases  1.383499e+04 -1971.6986
15     Supplies  2.391648e+03  -306.0760



# Q2. Which states are generating the highest sales but lowest profit?

In [75]:
state_analysis = df.groupby('State')[['Sales','Profit']].sum().reset_index()

state_analysis = state_analysis.sort_values(
    by=['Sales','Profit'],
    ascending=[False,True]
)

state_analysis.head(10)

             State         Sales     Profit
26        New York  1.002884e+07  7423.5411
7          Florida  1.000811e+07 -1103.3793
16        Michigan  5.011749e+06  3594.0831
3       California  4.042298e+04  6518.0483
35           Texas  3.021298e+04 -3771.4814
31    Pennsylvania  1.702902e+04 -4170.8204
9         Illinois  1.134017e+04 -1115.7864
27  North Carolina  1.126368e+04 -3559.7027
38      Washington  9.485668e+03  2476.1283
4         Colorado  8.049085e+03   434.9108



# Q3. Which customers are most valuable in terms of both sales and profit?

In [76]:
customer_value = df.groupby('Customer Name')[['Sales','Profit']].sum().reset_index()

customer_value = customer_value[
    (customer_value['Sales'] > customer_value['Sales'].mean()) &
    (customer_value['Profit'] > customer_value['Profit'].mean())
]

customer_value = customer_value.sort_values(
    by=['Sales','Profit'],
    ascending=[False,False]
)

customer_value.head(10)

          Customer Name       Sales    Profit
222  Lauren Leatherbury  5000396.76  873.9762

# Q4. Which shipping mode generates the highest average profit per order?

In [77]:
ship_profit = df.groupby('Ship Mode')['Profit'].mean().reset_index()

ship_profit = ship_profit.sort_values(
    by='Profit',
    ascending=False
)

ship_profit

        Ship Mode      Profit
0     First Class   26.241826
3  Standard Class   21.397751
2    Second Class   20.409689
1        Same Day -166.634671

# Q5. Which category performs best after considering discounts?

In [78]:
category_discount = df.groupby('Category').agg(
    Avg_Discount=('Discount','mean'),
    Total_Profit=('Profit','sum')
).reset_index()

category_discount = category_discount.sort_values(
    by='Total_Profit',
    ascending=False
)

category_discount

          Category  Avg_Discount  Total_Profit
1  Office Supplies      0.162521    12359.3230
2       Technology      0.142021     7988.6875
0        Furniture      0.178824    -1746.0089

# Q6. What percentage of total sales comes from the Top 10 customers?

In [79]:
top10_sales = df.groupby('Customer Name')['Sales'].sum().nlargest(10).sum()

total_sales = df['Sales'].sum()

percentage = (top10_sales / total_sales) * 100

print("Percentage of Sales from Top 10 Customers:", round(percentage, 2), "%")

Percentage of Sales from Top 10 Customers: 99.23 %

# Q7. Which sub-category gives the highest return per unit sold?

In [80]:
df["Return_per_Unit"] = df["Profit"] / df["Quantity"]

result = df.groupby("Sub-Category")["Return_per_Unit"].mean().sort_values(ascending=False)

result.head(10)

Sub-Category
Copiers        182.163400
Chairs          14.286621
Accessories     13.576080
Phones          11.582797
Envelopes        7.842680
Binders          7.210668
Storage          6.700983
Paper            6.095190
Labels           4.628807
Appliances       4.582802
Name: Return_per_Unit, dtype: float64

# Q8. Which customers are the most loyal based on number of orders?

In [81]:
loyal_customers = df.groupby("Customer Name")["Order ID"].count().sort_values(ascending=False)

loyal_customers.head(10)

Customer Name
Kunst Miller           11
Sam Craven             10
Shirley Daniels        10
Jonathan Doherty        9
Marina Lichtenstein     9
Carol Triggs            8
Stewart Visinsky        8
Naresj Patel            8
Chloris Kastensmidt     8
Matt Connell            7
Name: Order ID, dtype: int64

# Q9. Which segment is most stable in terms of profit?

In [82]:
segment_stability = df.groupby("Segment")["Profit"].std().sort_values()

segment_stability

Segment
Consumer       189.987021
Home Office    258.844735
Corporate      268.154328
Name: Profit, dtype: float64

# Q10. Which shipping mode is most cost-efficient (high profit, low discount)?

In [83]:
shipping_efficiency = df.groupby("Ship Mode").agg(
    Total_Profit=("Profit", "sum"),
    Avg_Discount=("Discount", "mean")
).reset_index()

shipping_efficiency = shipping_efficiency.sort_values(
    by="Total_Profit",
    ascending=False
)

shipping_efficiency

        Ship Mode  Total_Profit  Avg_Discount
3  Standard Class    12346.5022      0.162149
0     First Class     4802.2541      0.137978
2    Second Class     4286.0347      0.181286
1        Same Day    -2832.7894      0.176471